
[build]
  publish = "./public/"
  functions = "api/"

[[redirects]]
  # SSR and SPA
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 404
  
  # SPA only
  # from = "/*"
  # to = "/__app.html"
  # status = 404